### ISSUE TITLE
Question about Parallelization

### ISSUE THREAD

**Issue by stumarcus314** [snowberryfield/printemps#210]
Why did you parallelize PRINTEMPS with OpenMP rather than C++ threads (https://cplusplus.com/reference/thread/thread/) or pthreads (https://www.tutorialspoint.com/cplusplus/cpp_multithreading.htm)?

**Comment by snowberryfield** [comment]
Thank you for questions about parallelization.

I have implemented a parallelization scheme with only OpenMP, and have not tried other thread parallelization schemes such as std::thread. The reason why I choose OpenMP is that it has the advantage of being easy to implement. In addition, many of the processes parallelized in PRINTEMPS are relatively fine-grained, such as element-wise arithmetic operations of vectors, and I guessed that OpenMP is suitable.
